### ISSUE TITLE
 .unwrap, .serialize, .assign, .update, and .updateDeep

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-reflect#24]
To solve several issues that came from trying to make `DefineMap` generic, I propose the following `can-reflect` methods:

## `canReflect.unwrap(value)`

This will convert `value` into a plain javascript object, array or primitive type.  It can be passed something that responds to `.getValue` or something that `isListLike` or `.isMapLike` and will serialize to a `{}` or a `[]`.  This will run recursively.  

## `canReflect.serialize(value)`

This is just like `canReflect.toPlainJS` except it will look for a `can.serialize` symbol on objects before it recursively calls `toPlainJS`.

- related: #9

##  `canReflect.assign( value1, value2 )`

__For value-like:__

It will assign `value2` into `value1` if `value1` implements `.setValue`.  

__For map-like:__

This will copy values from `value2` into `value1`. 

__For list-like:__

This will end up doing a `.splice`, replacing the items of `value1` with the items of `value2.  If value1's length is greater than value2's length, the items in value1 at indexes larger than value2 will be left in place.

## `canReflect.update( value1, value2 )`

__For map-like:__

This will copy values from `value2` into `value1`. It will `deleteKeyValue` keys in `value1` that are not in `value2`.

__For list-like:__

This will replace the items in `value1` with the items in `value2`.

## `canReflect.updateDeep( value1, value2 )`

__For map-like:__

 - new `isPrimitive` -> `.setKeyValue()`
 - current is `isListLike`, new is`isListLike` -> `.update()`
 - current is `isMapLike`, new is `isMapLike` -> `.updateDeep()`

__For list-like:__

`DefineList`:

- Just does .replace on itself.

`can-list`:

 - current is `isMapLike`, new `isPOJO` -> `.updateDeep()` (borked implementation)
 - ELSE -> `.setKeyValue()` (should be a .splice)
 
at end ... update list with remaining items.

**Comment by justinbmeyer** [comment]
I think we need a generic `.set` too.  This would be like assign, but remove keys it couldn't find.

**Comment by justinbmeyer** [comment]
I also think `toPlain` and `serialize` will need to take a `useCID` option.  This will allow it to avoid cycles.

**Comment by frank-dspeed** [comment]
@justinbmeyer the generic set could be called apply its often used for apply settings or apply changes

**Comment by justinbmeyer** [comment]
It might be important to think about diffs here too.  Perhaps `.merge` for `diff` and `patch` type functionality?

## merge(value1, value2)

__For map-like:__

**Comment by chasenlehara** [comment]
@phillipskevin Should we leave this open?
