### ISSUE TITLE
Look into where we can improve performance

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-reflect#32]
In [today’s contributors meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-07-14/684), we talked about how the performance improvements to `can-stache` with `can-reflect` weren’t as good as the initial prototypes. This issue is for looking into what we can do to make things faster.

**Comment by justinbmeyer** [comment]
This should be moved to can-stache

**Comment by andrejewski** [comment]
Issue moved to [canjs/can-stache #244](https://github.com/canjs/can-stache/issues/244) via [**ZenHub**](https://www.zenhub.com/)
