### ISSUE TITLE
Decorate Map, WeakMap, Set, and WeakSets to work

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-reflect#42]
If `can-relfect` is loaded, I think it should decorate some base types: `Map`, `Set`, `WeakMap`, `WeakSet`.

I think this might mean we want to bring in `Promise` as well.  Thoughts?

**Comment by justinbmeyer** [comment]
we can't make looping through `WeakMap` work

**Comment by phillipskevin** [comment]
Seems like this might be going against the "remove side effects" mantra. Since it is Symbols, maybe it is ok?

When would you want to use these where you couldn't use a mixin to do the decorating for you? Or alternatively, where you couldn't import like a `can-weak-map` module that would extend `WeakMap` and add the symbols.

**Comment by justinbmeyer** [comment]
> Seems like this might be going against the "remove side effects" mantra. Since it is Symbols, maybe it is ok?

Yes, symbols make this ok.  You could have multiple versions of `can-reflect` and `can-symbol` ... each decorating `Map` multiple times, but still working.  This is because the `symbol`s are unique and non-conflicting.  Maybe I need to explain this better in my article.

>  When would you want to use these where you couldn't use a mixin to do the decorating for you? Or alternatively, where you couldn't import like a can-weak-map module that would extend WeakMap and add the symbols.

I'm not totally sure what you mean here, but why would you ever extend `WeakMap`?  This would require everyone to use that version of `WeakMap`.  Gross.  Symbols again here are perfect.  They aren't really "known" except by https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols

**Comment by justinbmeyer** [comment]
> Seems like this might be going against the "remove side effects" mantra. Since it is Symbols, maybe it is ok?

Even if we had to lock-down `can-symbol` and `can-reflect` so there could only be 1, this would still be the preferable solution because the alternate solution is `can-reflect` or `can-stache-key` being omniscient.  They would have to know every possible type.
