### ISSUE TITLE
Typeof returns a string

### ISSUE THREAD

**Issue by jeroencornelissen** [canjs/can-reflect#46]
We're seeing a lot of errors in our environment with IE11 users.
This line is the issue: [if(typeof WeakSet !== undefined) { ](https://github.com/canjs/can-reflect/blob/1d9c253e50213c03799d7d92c64d873b9b615f87/types/set.js#L21)

I've created a [PR](https://github.com/canjs/can-reflect/pull/45) to fix this.

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-reflect/pull/45.

**Comment by phillipskevin** [comment]
This is published in [can-reflect@1.4.1](https://github.com/canjs/can-reflect/releases/tag/v1.4.1). Thanks for the fix!
