### ISSUE TITLE
Remaining methods to add

### ISSUE THREAD

**Issue by imaustink** [canjs/can-reflect#47]
The following is a todo list copied from the readme after this change: https://github.com/canjs/can-reflect/commit/70842edbfa8155d475c974d7254312219735db33
 - [x] `.deleteKeyValue`, `.get` and `.set` aliases
 - [x] `addKeys` / `removeKeys`
 - [ ] `isInitializing`

**Comment by phillipskevin** [comment]
@imaustink can you give this a better name / description? The way it is, I can't tell what this issue is about.

**Comment by imaustink** [comment]
@phillipskevin I've updated the title and description with what I know. Looks like @justinbmeyer originally made the list here: https://github.com/canjs/can-reflect/commit/38711344116c55c139c04765f1378a56a7dbd6b7

**Comment by justinbmeyer** [comment]
closing for #2
