### ISSUE TITLE
Serializing a Ref creates an empty object in the cache

### ISSUE THREAD

**Issue by imaustink** [canjs/can-reflect#63]
When serializing a `Ref` and providing a `MapType` to cache with, the cached value is set to an empty object.

[Here](https://github.com/canjs/can-reflect/blob/master/reflections/shape/shape.js#L95) the value to serialize and a pointer to its cache is provided. Normally, an object would be serialized into a POJO and its properties would be applied to the cache reference. Since in this case, the serialized value is a string, the pointer to its cache is not updated.

To fix this, would it be acceptable to simply check for a string [here](https://github.com/canjs/can-reflect/blob/master/reflections/shape/shape.js#L99) and set the cache value?

**Comment by justinbmeyer** [comment]
ran into this on bitcentive, going to fix
