### ISSUE TITLE
support for getting/setting expando properties

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-reflect#66]
can-connect uses a custom "expando" solution for setting special properties on Maps and DefineMaps.  See: https://github.com/canjs/can-connect/blob/932be9f8f6fc084d77f00bb2d7552c049dc7123e/can/map/map.js#L16

The problem with this solution is that it expects certain keys to exist (either `attr` or `_data`) on every object.  This may not be the case when we get outside of can-maps and defined objects.

Instead, we should have a can-reflect mechanism for setting and reading expando properties on objects, which would be similar to normal key/value setting/getting but with a fallback for sealed objects and special objects (which would be symbol-implemented).

**Comment by justinbmeyer** [comment]
This is provided by `can.defineInstanceKey` symbol.
