### ISSUE TITLE
Create canReflect.hasKey

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-reflect#93]
Similar to `hasOwnKey`, but should walk the proto chain.

**Comment by frank-dspeed** [comment]
@phillipskevin can-stache/expressions is using hasKey that is not implamented
 canReflect.hasKey is not a function

and i am not sure what this is about 

you mean copy paste and walk over .__proto__.__proto__ ?

**Comment by phillipskevin** [comment]
This was closed by https://github.com/canjs/can-reflect/pull/95.
