### ISSUE TITLE
can-reflect should avoid can-cid as a dependency

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-reflect#98]
CanJS 4.0 avoids needing can-cid because it uses ES Map and Set everywhere.

This creates a difficulty with the current `.serialize()` implementation that uses CIDMap.

There are a few ways around this:

1.  Make sure all consumers of `.serialize()` MUST pass a map type. 3.0 can pass CIDMap, 4.0 can pass Map.
2.  Make it so all consumers of `.serialize()` in browsers that don't support `Map` MUST pass a map type.  This means that 3.0 should pass `CIDMap`, but 4.0 doesn't have to.
3.  Don't support cycles if `Map` isn't supported by the browser.
4.  If `Map` isn't supported, fall back to an Array-based `.indexOf()` solution that will be `O(n^2)`,
5. Go can-reflect 2.0, which will assume `Map`

**Comment by matthewp** [comment]
I think I'll just create a minimal map using arrays for non-supporting browsers since that's easiest.
